name: publish
run-name: publish

permissions:
  contents: read
  packages: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: collect
        run: |
          mkdir -p input
          cp \
            ./bylaw-account/bylaw-account.md \
            ./agreement/welcoming/README.md \
            ./bylaw-master/bylaw-master.md \
            ./bylaw-welcoming/bylaw-welcoming.md \
            ./input/
      - name: build
        uses: docker://ghcr.io/8128-33550336/regulations-generator:latest
        with:
          args: -a $GITHUB_WORKSPACE/input $GITHUB_WORKSPACE/output
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3

